# Generated by Django 5.2.6 on 2025-09-19 06:48

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('carousel', 6)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 100, 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'max_length': 250, 'required': False}), 3: ('wagtail.blocks.URLBlock', (), {'required': False}), 4: ('wagtail.blocks.StructBlock', [[('image', 0), ('title', 1), ('subtitle', 2), ('link', 3)]], {}), 5: ('wagtail.blocks.ListBlock', (4,), {'label': 'Slides'}), 6: ('wagtail.blocks.StructBlock', [[('slides', 5)]], {})}, null=True),
        ),
    ]
