# Generated by Django 5.2.6 on 2025-09-17 06:09

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_ccorppage_llcpage_nonprofitpage_scorppage'),
    ]

    operations = [
        migrations.AddField(
            model_name='ccorppage',
            name='intro',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='intro',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='llcpage',
            name='intro',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='nonprofitpage',
            name='intro',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='scorppage',
            name='intro',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
