# Generated by Django 5.2.6 on 2025-09-16 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='footermenu',
            options={'verbose_name': 'Footer Menu', 'verbose_name_plural': 'Footer Menus'},
        ),
        migrations.AlterModelOptions(
            name='menus',
            options={'verbose_name': 'Menu', 'verbose_name_plural': 'Menus'},
        ),
    ]
