# Generated by Django 5.2.6 on 2025-09-16 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_footermenu_options_alter_menus_options'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='menus',
            name='menu_image',
            field=models.ForeignKey(blank=True, help_text='Optional icon for the menu', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
