# Generated by Django 5.2.6 on 2025-09-17 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_faq_package_service_testimonial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FAQ',
        ),
        migrations.DeleteModel(
            name='Package',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='Testimonial',
        ),
    ]
